
import javax.swing.ButtonGroup;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lolog
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
                // Create a ButtonGroup and add your radio buttons to it in the constructor
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(mediummode);
        buttonGroup.add(hardmode);
        buttonGroup.add(easymode);
    }
    public boolean get_easymode(){
        return easymode.isSelected();
    }
    public boolean get_mediummode(){
        return mediummode.isSelected();
    }
    public boolean get_hardmode(){
        return hardmode.isSelected();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        friendplayer = new javax.swing.JButton();
        aiplayer = new javax.swing.JButton();
        easymode = new javax.swing.JRadioButton();
        mediummode = new javax.swing.JRadioButton();
        hardmode = new javax.swing.JRadioButton();
        exit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NIM'S GAME ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 20, 440, 80);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("choose to play :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 130, 230, 30);

        friendplayer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        friendplayer.setForeground(new java.awt.Color(0, 0, 51));
        friendplayer.setText("with friend");
        friendplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friendplayerActionPerformed(evt);
            }
        });
        jPanel1.add(friendplayer);
        friendplayer.setBounds(180, 270, 180, 30);

        aiplayer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        aiplayer.setForeground(new java.awt.Color(0, 0, 51));
        aiplayer.setText("with PC");
        aiplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aiplayerActionPerformed(evt);
            }
        });
        jPanel1.add(aiplayer);
        aiplayer.setBounds(180, 180, 180, 30);

        easymode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        easymode.setForeground(new java.awt.Color(255, 255, 255));
        easymode.setText("easy");
        easymode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easymodeActionPerformed(evt);
            }
        });
        jPanel1.add(easymode);
        easymode.setBounds(210, 230, 53, 25);

        mediummode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mediummode.setForeground(new java.awt.Color(255, 255, 255));
        mediummode.setText("medium");
        mediummode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediummodeActionPerformed(evt);
            }
        });
        jPanel1.add(mediummode);
        mediummode.setBounds(320, 230, 78, 25);

        hardmode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hardmode.setForeground(new java.awt.Color(255, 255, 255));
        hardmode.setText("hard");
        hardmode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardmodeActionPerformed(evt);
            }
        });
        jPanel1.add(hardmode);
        hardmode.setBounds(460, 230, 54, 25);

        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 0, 51));
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(520, 400, 72, 27);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("*");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 250, 120, 90);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("*");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 160, 120, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void friendplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friendplayerActionPerformed
     PlayWithFreind m = new PlayWithFreind ();
     m.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_friendplayerActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0); 
        //this.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed
//to make the three jbutton clickable 
 
    private void easymodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easymodeActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_easymodeActionPerformed

    private void mediummodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediummodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediummodeActionPerformed

    private void hardmodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardmodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hardmodeActionPerformed

    private void aiplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aiplayerActionPerformed
        // TODO add your handling code here:
       PlayWithPC newframe=new PlayWithPC();
       newframe.setVisible(true);
    }//GEN-LAST:event_aiplayerActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aiplayer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton easymode;
    private javax.swing.JButton exit;
    private javax.swing.JButton friendplayer;
    private javax.swing.JRadioButton hardmode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mediummode;
    // End of variables declaration//GEN-END:variables



}
